# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
# name: Your Name

name: Mohanad Elsafty
title: Senior Data Engineer
location: Singapore, Singapore
phone: +65-88498090
email: mohanad.elsafty@outlook.com
website: https://mohan3d.github.io/resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mohan3d
linkedin_username: mohanad-elsafty

# Additional icon links
additional_links:
- title: CV
  icon: fa fa-file-text
  # url: https://mohan3d.github.io/resume/mohanad.elsafty.cv.pdf
  url: mohanad.elsafty.cv.pdf

- title: Bitbucket
  icon: fab fa-bitbucket
  url: https://bitbucket.org/mohan3d/workspace/repositories

- title: Hackerrank
  icon: fab fa-brands fa-hackerrank
  url: https://www.hackerrank.com/mohaned

# - title: Leetcode
#   icon: fa fa-solid fa-code
#   url: https://leetcode.com/mohan3d

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Data Engineer with a proven track record of optimizing big data pipelines and architecting scalable solutions. 
  My expertise in Amazon AWS, Apache Spark, Hadoop, Ozone and distributed systems has empowered me to enhance performance and efficiency across projects. 
  I like working on distributed systems and data on a big scale.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Singtel
        sub_title: Technical Lead
        caption: Aug 2023 - Present
        link: https://www.singtel.com
        quote: >
          Singapore Telecommunications
        description: |
          - Building the data fabric solution of Singtel
          > Apache Spark, Apache Hadoop, Apache Airflow, Amazon AWS, Microsot Azure, Python, Rust, Scala.

      - layout: left
        title: Shopee
        sub_title: Senior Data Infrastructure Engineer
        caption: Jan 2021 - Aug 2023
        link: https://shopee.sg
        quote: >
          E-commerce company
        description: |
          - Enhanced Spark history server, resulting in 80% performance improvement with larger datasets.
          - Developed logs aggregation for Yarn/HDFS logs, saving 3 hours weekly.
          - Designed low-memory fingerprint for extended offline analysis of FSIMAGE.
          - Engineered block-based InputFormat for DistCp, shortening data transfer time by 20%.
          - Enhanced DFSClient and NameNode for read/write operations.
          - Engineered petabyte-scale data Retention Service, saving 15% of storage.
          - Architected universal s3gateway solution for multiple clusters access.
          - Devised efficient fair call queue and Quality of Service mechanisms for s3gateway.
          > Apache Spark, Apache Hadoop/HDFS, Apache Ozone, Apache Airflow, Apache Ratis, AWS, RocksDB, Kubernetes, Golang, Scala, Java, JavaScript, C++
      
      - layout: left
        title: GFG - Global Fashion Group
        sub_title: Data Engineer
        caption: Jan 2019 - Dec 2020
        link: https://global-fashion-group.com
        quote: >
          E-commerce company
        description: |
          - Revamped ZMM system, reducing runtime by 41% and cost by 70.6%.
          - Optimized SQL queries on Amazon Redshift, reducing ingestion time by 66%.
          - Pioneered media attribution model based on Hidden Markov model.
          - Collaborated on visualization of model outcomes using Apache Superset.
          - Led development of automated price prediction system, optimizing training time.
          - Devised data ingestion techniques and optimized cluster size.
          > AWS(S3, EMR, ECS, EKS, CodeBuild), Apache Airflow, Python, PySpark, R, SQL, Pandas, NumPy, Notebooks

      - layout: left
        title: SigmaProIT
        sub_title: Full Stack Developer
        caption: Dec 2017 - Sep 2018
        link: https://sigmaproit.com
        quote: >
          IT Services and IT Consulting 
        description: |
          - Developed VOIP android application and dedicated webservice.
          - Participated in mobile application development and optimized backend API response time.
          > Python, Django, NodeJS, Angular, Ionic

      - layout: left
        title: Cloudypedia
        sub_title: Software Engineer
        caption: Apr 2016 - Nov 2017
        link: https://www.cloudypedia.com
        quote: >
          IT Services and IT Consulting 
        description: |
          - Constructed certification module with Arabic language support.
          - Built filter and tagging module for optimized search on OpenEDX.
          - Designed GoogleAppEngine-based web application and crafted python wrappers for G-Suite APIs.
          > Google Cloud, GoogleAppEngine, Python, Django, ElasticSearch, OpenEDX

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Ain Shams University
        sub_title: B.Sc. in Computer Science and Information Systems
        caption: 2011 - 2015
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: mohan3d/resume

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
